/* ************* BANCO DE DADDOS INTRANET V1.0 ************
VERSÃO 1.0
MYSQL
VINICIUS FAGUNDES TAVARES

**********************************************************/

/* ************** CADASTROS *-************************/
CREATE TABLE GRUPO(
CDGRUPOE INT NOT NULL AUTO_INCREMENT,
NMGRUPO VARCHAR (50) NOT NULL
CHAVEACESSO VARCHAR (100) NOT NULL,
PRIMARY KEY (CDGRUPOE)
);

CREATE TABLE EMPRESAS (
CDEMPRESA INT NOT NULL AUTO_INCREMENT,
CDGRUPOE INT NOT NULL ,
NMEMPRESA VARCHAR (50) NOT NULL,
DTCRIACAO DATE CURRENT_DATE,
CEP VARCHAR (40),
CNPJ VARCHAR (30) NOT NULL,
ATIVO INT (1) NOT NULL,
PRIMARY KEY (CDEMPRESA), 
UNIQUE KEY 'CNPJ_KEY' ('CNPJ'),
FOREIGN KEY (CDGRUPOE)REFERENCES GRUPO

);

CREATE TABLE PESSOAS(
	CDPESSOA   INT  NOT NULL AUTO_INCREMENT,
	CDEMPRESA INT NOT NULL, 
	CPF VARCHAR (17) NOT NULL,
	NOME VARCHAR(70) NOT NULL,
	FONE NUMBER (25),
	ATIVO CHAR (1) NOT NULL,
	CDTIPOPESSOA INT (10) NOT NULL,
	DTCRIACAO DATE CURRENT_DATE,
	CEP VARCHAR (40), 
	PRIMARY KEY (CDPESSOA),
	UNIQUE KEY 'CPF_KEY' ('CPF'),
	FOREIGN KEY (CDEMPRESA)REFERENCES EMPRESAS
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;	

CREATE TABLE PERFIL (
CDPERFIL INT NOT NULL AUTO_INCREMENT,
DSPERFIL VARCHAR (25) NOT NULL,
DTCRIACAO DATE CURRENT_DATE,
ATIVO INT (1), 
PRIMARY KEY (CDPERFIL)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;	

CREATE TABLE CARGOS (
CDCARGO INT NOT NULL AUTO_INCREMENT,
DSCARGO VARCHAR (25) NOT NULL,
DTCRIACAO DATE CURRENT_DATE,
ATIVO INT (1), 
PRIMARY KEY (CDCARGO)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;	

CREATE TABLE USUARIOS (
CDUSUARIO INT NOT NULL AUTO_INCREMENT,
CDPESSOA INT NOT NULL,
CDPERFIL INT NOT NULL,
CDCARGO INT NOT NULL,
EMAIL VARCHAR (40) NOT NULL,
SENHA VARCHAR (20) NOT NULL,
DTCRIACAO DATE CURRENT_DATE,
DTFIMACE DATE ,
	PRIMARY KEY (CDUSUARIO),
	FOREIGN KEY (CDPESSOA)REFERENCES PESSOAS,
	FOREIGN KEY (CDPERFIL)REFERENCES PERFIL,
    FOREIGN KEY (CDCARGO)REFERENCES CARGOS,
	UNIQUE KEY 'EMAIL_KEY' ('EMAIL')
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;	
